MailOrderMVCConsume/Controllers/RefillController.cs
using MailOrderMVCConsume.DTO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace MailOrderMVCConsume.Controllers
{
    public class RefillController : Controller
    {
        public IActionResult RefillStatus(int SubscriptionId)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:2393");
            var token = HttpContext.Session.GetString("JWTToken");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            HttpResponseMessage response = client.GetAsync("/api/Refill/viewRefillStatus/" + SubscriptionId).Result;

            if (response.StatusCode == HttpStatusCode.OK)
            {
                List<RefillOrderDTO> refills = response.Content.ReadAsAsync<List<RefillOrderDTO>>().Result;
                return View(refills);
            }
            else if (response.StatusCode == HttpStatusCode.Unauthorized)
                return Unauthorized();
            else 
                return NoContent();
        }
        public IActionResult ConfirmRefill(int RefillId, int SubscriptionId)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:2393");
            var token = HttpContext.Session.GetString("JWTToken");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            StringContent content = new StringContent(JsonConvert.SerializeObject(""), Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync("/api/Refill/requestAdhocRefill/" + SubscriptionId + "/" + RefillId, content).Result;

            if (response.StatusCode == HttpStatusCode.OK)
            {
                ViewBag.Message = "Payment Confirmed. Refill Completed will Reach in within 3 hours";
                return RedirectToAction("GetAllSubscriptions","Subscription");
            }
            else if (response.StatusCode == HttpStatusCode.Unauthorized)
                return Unauthorized();
            else
                return NoContent();
        }

        public IActionResult GetRefillDuesAsOfDate()
        {
            return View();
        }
        [HttpPost]
        public IActionResult GetRefillDuesAsOfDate(RefillDueAsDateDTO refillDue)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:2393");
            var token = HttpContext.Session.GetString("JWTToken");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            DateTime dt = refillDue.FromDate;
            
            HttpResponseMessage response = client.GetAsync("/api/Refill/getRefillDuesAsOfDate/"+refillDue.SubscriptionId+"/"+ dt.ToString("yyyy-MM-dd")).Result;

            if (response.StatusCode == HttpStatusCode.OK)
            {
                List<RefillOrderDTO> refills = response.Content.ReadAsAsync<List<RefillOrderDTO>>().Result;
                return View("RefillDueAsDate", refills);
            }
            else if (response.StatusCode == HttpStatusCode.Unauthorized)
                return Unauthorized();
            else
                return NoContent();
        }

        public IActionResult RefillDueAsDate(List<RefillOrderDTO> refills)
        {
            return View(refills);
        }
    }
}

MailOrderMVCConsume/Controllers/SubscriptionController.cs
using MailOrderMVCConsume.DTO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace MailOrderMVCConsume.Controllers
{
    public class SubscriptionController : Controller
    {
        public IActionResult CreatePrescription()
        {
            int MemberId = (int)HttpContext.Session.GetInt32("MemberId");
            ViewBag.Id = MemberId;
            return View();
        }
        [HttpPost]
        public IActionResult CreatePrescription(MemberPrescriptionDTO prescription)
        {
            prescription.MemberId= (int)HttpContext.Session.GetInt32("MemberId");
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:53504");
            var token = HttpContext.Session.GetString("JWTToken");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            StringContent content = new StringContent(JsonConvert.SerializeObject(prescription), Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync("/api/Subscription/createPrescription", content).Result;

            if (response.StatusCode == HttpStatusCode.OK)
            {
                int MemberId = (int)HttpContext.Session.GetInt32("MemberId");
                ViewBag.Id = MemberId;
                ViewBag.Message = "Prescription Added";
                return View();
            }
            else if (response.StatusCode == HttpStatusCode.Unauthorized)
                return Unauthorized();
            else
            {
                ViewBag.Message = "Could not add prescription due to drug not found";
                return View();
            }
        }
        public IActionResult CreateSubscription(int prescriptionId)
        {
            int MemberId = (int)HttpContext.Session.GetInt32("MemberId");
            ViewBag.Id = MemberId;
            ViewBag.PrescriptionId = prescriptionId;
            return View();
        }
        [HttpPost]
        public IActionResult CreateSubscription(SubscriptionDTO subscription)
        {
            subscription.MemberId = (int)HttpContext.Session.GetInt32("MemberId");
            subscription.Token = HttpContext.Session.GetString("JWTToken");
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:53504");
            var token = HttpContext.Session.GetString("JWTToken");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            StringContent content = new StringContent(JsonConvert.SerializeObject(subscription), Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync("/api/Subscription/Subscribe", content).Result;

            if (response.StatusCode == HttpStatusCode.OK)
            {
                int MemberId = (int)HttpContext.Session.GetInt32("MemberId");
                ViewBag.Id = MemberId;
                string message = response.Content.ReadAsStringAsync().Result;
                ViewBag.Message = message;
                return View();
            }
            else if (response.StatusCode == HttpStatusCode.Unauthorized)
                return Unauthorized();
            else
            {
                string message = response.Content.ReadAsStringAsync().Result;
                ViewBag.Message = message;
                return View();
            }
        }

        public IActionResult UnSubscription(int SubscriptionId)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:53504");
            var token = HttpContext.Session.GetString("JWTToken");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            StringContent content = new StringContent(JsonConvert.SerializeObject(token), Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync("/api/Subscription/UnSubscribe/"+SubscriptionId,content).Result;

            if (response.StatusCode == HttpStatusCode.OK)
            {
                ViewBag.Message = response.Content.ReadAsStringAsync().Result;
                //return RedirectToAction("GetAllSubscriptions");
                return View();
            }
            else if (response.StatusCode == HttpStatusCode.Unauthorized)
                return Unauthorized();
            else
            {
                ViewBag.Message = response.Content.ReadAsStringAsync().Result;
                //return RedirectToAction("GetAllSubscriptions");
                return View();
            }
        }

        public IActionResult GetAllPrescriptions()
        {
            int MemberId = (int)HttpContext.Session.GetInt32("MemberId");
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:53504");
            var token = HttpContext.Session.GetString("JWTToken");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            HttpResponseMessage response = client.GetAsync("/api/Subscription/getAllPrescriptions/"+MemberId).Result;

            if (response.StatusCode == HttpStatusCode.OK)
            {
                List<PrescriptionDetailsDTO> prescriptions = response.Content.ReadAsAsync<List<PrescriptionDetailsDTO>>().Result;
                return View(prescriptions);
            }
            else if (response.StatusCode == HttpStatusCode.Unauthorized)
                return Unauthorized();
            else
                return NoContent();
        }
        public IActionResult GetAllSubscriptions()
        {
            int MemberId = (int)HttpContext.Session.GetInt32("MemberId");
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:53504");
            var token = HttpContext.Session.GetString("JWTToken");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            HttpResponseMessage response = client.GetAsync("/api/Subscription/getAllSubscriptions/"+MemberId).Result;

            if (response.StatusCode == HttpStatusCode.OK)
            {
                List<SubscriptionDetailsDTO> subscriptions = response.Content.ReadAsAsync<List<SubscriptionDetailsDTO>>().Result;
                return View(subscriptions);
            }
            else if (response.StatusCode == HttpStatusCode.Unauthorized)
                return Unauthorized();
            else
                return NoContent();
        }

    }
}

MailOrderMVCConsume/Views/Subscription/CreatePrescription.cshtml
@model MailOrderMVCConsume.DTO.MemberPrescriptionDTO

@{
    ViewData["Title"] = "CreatePrescription";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("@ViewBag.Message");
        };
    </script>
}
<h1>Create Prescription</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePrescription">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MemberId" class="control-label">Member Id</label>
                <input asp-for="MemberId" class="form-control" value="@ViewBag.Id" disabled/>
                <span asp-validation-for="MemberId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InsurancePolicyNumber" class="control-label">Insurance Policy Number</label>
                <input asp-for="InsurancePolicyNumber" class="form-control" />
                <span asp-validation-for="InsurancePolicyNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InsuranceProvider" class="control-label">Insurance Provider</label>
                <input asp-for="InsuranceProvider" class="form-control" />
                <span asp-validation-for="InsuranceProvider" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrescriptionDate" class="control-label">Prescription Date</label>
                <input asp-for="PrescriptionDate" class="form-control" />
                <span asp-validation-for="PrescriptionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DrugId" class="control-label">Drug Id</label>
                <input asp-for="DrugId" class="form-control" />
                <span asp-validation-for="DrugId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DosagePerDay" class="control-label">Dosage Per Day</label>
                <input asp-for="DosagePerDay" class="form-control" />
                <span asp-validation-for="DosagePerDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrescriptionCourseInWeeks" class="control-label">Prescription Course In Weeks</label>
                <input asp-for="PrescriptionCourseInWeeks" class="form-control" />
                <span asp-validation-for="PrescriptionCourseInWeeks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctorDetails" class="control-label">Doctor Details</label>
                <input asp-for="DoctorDetails" class="form-control" />
                <span asp-validation-for="DoctorDetails" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

MailOrderMVCConsume/Views/Subscription/CreateSubscription.cshtml
@using MailOrderMVCConsume.DTO
@model MailOrderMVCConsume.DTO.SubscriptionDTO

@{
    ViewData["Title"] = "CreateSubscription";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("@ViewBag.Message");
        };
    </script>
}
<h1>Add Subscription To Prescription</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateSubscription">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MemberId" class="control-label">Member Id</label>
                <input asp-for="MemberId" class="form-control" value="@ViewBag.Id" disabled />
                <span asp-validation-for="MemberId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubscriptionDate" class="control-label">Subscription Date</label>
                <input asp-for="SubscriptionDate" class="form-control" />
                <span asp-validation-for="SubscriptionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrescriptionId" class="control-label">Prescription Id</label>
                <input asp-for="PrescriptionId" class="form-control" value="@ViewBag.PrescriptionId"/>
                <span asp-validation-for="PrescriptionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RefillOccurrence" class="control-label">Refill Occurrence</label>
                @*<input asp-for="RefillOccurrence" class="form-control" />*@

                @Html.DropDownListFor(m => m.RefillOccurrence,
                new SelectList(Enum.GetValues(typeof(Occurrence))),
                "Select Occurrence", new { @class = "form-control" })

                <span asp-validation-for="RefillOccurrence" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberLocation" class="control-label">Member Location</label>
                <input asp-for="MemberLocation" class="form-control" />
                <span asp-validation-for="MemberLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add Subcription" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

MailOrderMVCConsume/Views/Subscription/GetAllPrescriptions.cshtml
@model IEnumerable<MailOrderMVCConsume.DTO.PrescriptionDetailsDTO>

@{
    ViewData["Title"] = "GetAllPrescriptions";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h1>Get All Prescriptions</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PrescriptionId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MemberId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InsurancePolicyNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InsuranceProvider)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrescriptionDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DrugId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DosagePerDay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrescriptionCourseInWeeks)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoctorDetails)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PrescriptionId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MemberId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InsurancePolicyNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InsuranceProvider)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrescriptionDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DrugId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DosagePerDay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrescriptionCourseInWeeks)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoctorDetails)
            </td>
            <td>
                @Html.ActionLink("Subscribe", "CreateSubscription",new { PrescriptionId=item.PrescriptionId }) 
            </td>
        </tr>
}
    </tbody>
</table>

MailOrderMVCConsume/Views/Subscription/GetAllSubscriptions.cshtml
@model IEnumerable<MailOrderMVCConsume.DTO.SubscriptionDetailsDTO>

@{
    ViewData["Title"] = "GetAllSubscriptions";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

@if (TempData["Message"] != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert(TempData["Message"]);
        };
    </script>
}

<h1>Get All Subscriptions</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SubscriptionId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MemberId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubscriptionDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrescriptionId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RefillOccurrence)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MemberLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubscriptionStatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SubscriptionId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MemberId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubscriptionDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrescriptionId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RefillOccurrence)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MemberLocation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubscriptionStatus)
                </td>
                <td>
                    @Html.ActionLink("Refill Status", "RefillStatus", "Refill", new { SubscriptionId = item.SubscriptionId }) |
                    @Html.ActionLink("Unsubscribe", "UnSubscription","Subscription", new { SubscriptionId = item.SubscriptionId }) @*|
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
                </td>
            </tr>
        }
    </tbody>
</table>

MailOrderMVCConsume/Views/Subscription/UnSubscription.cshtml
@{
    ViewData["Title"] = "UnSubscription";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("@ViewBag.Message");
        };
    </script>
}

@Html.ActionLink("View All Subscriptions", "GetAllSubscriptions")